spring:

  datasource:
    url: "jdbc:postgresql://localhost:5432/learntocode"
    username: "postgres"
    password: "postgres"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  flyway:
    placeholderReplacement: false
    locations:
      - classpath:db/migration

jwtSecret: "longsecurejwtsecret"
jwtExpirationMs: "86400000"