spring:

  datasource:
    url: "jdbc:${DATABASE_URL}"
    username: "${DATABASE_USERNAME}"
    password: "${DATABASE_PASSWORD}"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  flyway:
    placeholderReplacement: false
    locations:
      - classpath:db/migration

  mail:
    host: smtp.office365.com
    port: 587
    username: "${EMAIL_USERNAME}"
    password: "${EMAIL_PASSWORD}"

    properties:
      mail:
        smtp:
          starttls:
            enable: true


jwtSecret: "${JWT_SECRET}"
jwtExpirationMs: "86400000"
frontUrl: "${FRONT_URL}"
email: "${EMAIL_PASSWORD}"