spring:

  profiles:
    active: dev

  datasource:
    url: "jdbc:postgresql://localhost:5432/learntocode"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  mail:
    host: smtp.office365.com
    port: 587
    username: "${EMAIL}"
    password: "${EMAIL_PASSWORD}"

    properties:
      mail:
        smtp:
          starttls:
            enable: true


jwtSecret: "${JWT_SECRET}"
jwtExpirationMs: "86400000"
frontUrl: "${FRONT_URL}"
email: "${EMAIL}"